version: '3.8'
 
services:

  backend:

    build:

      context: ./fastapi_backend

      dockerfile: Dockerfile

    ports:

      - "8000:8000"

    env_file:

      - ./fastapi_backend/.env

    volumes:

      - ./fastapi_backend/credentials:/app/credentials
 
  frontend:

    build:

      context: ./streamlit_frontend

      dockerfile: Dockerfile

    ports:

      - "8501:8501"

    depends_on:

      - backend

    environment:

      - FASTAPI_BACKEND_URL=http://backend:8000/api/v1
 
networks:

  default:

    driver: bridge
 